# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HCLog' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HCLog

  pod 'CocoaLumberjack', '3.4.2'
  pod 'Antenna'
end
